### ISSUE TITLE
Script is not Python 3.X proof in AWS Lambda Functions

### ISSUE THREAD

**Issue by eelkonio** [orzarchi/terraform-aws-cloudflare-security-group#1]
Python 2 is not supported by AWS Lambda Functions anymore, very soon. That means this script will not work anymore as requests cannot be used anymore from botocore. This partial rewrite of the first part of the script works though:

```
import os
import boto3
import urllib3
import json

def get_cloudflare_ip_list():
    # Call the CloudFlare API and return a list of IPs
    http = urllib3.PoolManager()
    response = http.request('GET',
                            'https://api.cloudflare.com/client/v4/ips',
                            #body = json.dumps(some_data_structure),
                            headers = {'Content-Type': 'application/json'},
                            retries = False)
    temp = json.loads(response.data.decode('utf-8'))

    if 'result' in temp and 'ipv4_cidrs' in temp['result']:
        return temp['result']['ipv4_cidrs']

    raise Exception("Cloudflare response error")
```

**Comment by orzarchi** [comment]
Hey sorry, didn't notice this.
Can you submit a PR?

**Comment by edvsuperbrave** [comment]
That I can do, of course!

**Comment by edvsuperbrave** [comment]
No, I can't! 

I've checkout out your repo, created a new branch but I have no write-access to your repo. That makes creating a PR a bit cumbersome. ;)

`$ git push --set-upstream origin edv-python3-update
Enter passphrase for key '/home/eelko/.ssh/id_rsa': 
ERROR: Permission to orzarchi/terraform-aws-cloudflare-security-group.git denied to edvsuperbrave.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by orzarchi** [comment]
Hey, you need to fork it and PR from there
