### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by phivid** [orzarchi/terraform-aws-cloudflare-security-group#4]
Is it possible to tag repo when merge is applied @orzarchi ?
For example, my [pull request](https://github.com/orzarchi/terraform-aws-cloudflare-security-group/pull/3) was not tagged when merged. 😅

**Comment by orzarchi** [comment]
You got it.
As you can see, this module isn't very maintained, it's still in the old terraform syntax 👴

**Comment by phivid** [comment]
Yes, I saw it. 😅 
But it seems like this is the only one that manage this topic in terraform registry 😄
