### ISSUE TITLE
AccessDeniedException:  status code: 403 on aws_lambda_function.update-ips

### ISSUE THREAD

**Issue by antigenius0910** [orzarchi/terraform-aws-cloudflare-security-group#7]
Hi,

thanks for this awesome module, I am trying to apply it through GitHub action and somehow I always stuck here
```
Run terraform apply -auto-approve tfplan
/home/runner/work/_temp/ed4cdf7a-6a80-4b4d-8248-b51e16b5f7c3/terraform-bin apply -auto-approve tfplan
aws_security_group_rule.egress_https[0]: Creating...
aws_security_group_rule.egress_http[0]: Creating...
aws_iam_policy.policy[0]: Creating...
aws_iam_policy.policy[0]: Creation complete after 0s [id=arn:aws:iam::***:policy/lambda-cloudflare-policy]
aws_iam_role.iam_for_lambda[0]: Creating...
aws_iam_role.iam_for_lambda[0]: Creation complete after 0s [id=lambda-cloudflare-role]
aws_iam_role_policy_attachment.policy[0]: Creating...
aws_security_group_rule.egress_https[0]: Creation complete after 1s [id=sgrule-3666656408]
aws_iam_role_policy_attachment.policy[0]: Creation complete after 1s [id=lambda-cloudflare-role-20211130040932510500000001]
aws_cloudwatch_event_rule.cloudflare-update-schedule[0]: Creating...
aws_cloudwatch_event_rule.cloudflare-update-schedule[0]: Creation complete after 0s [id=cloudflare-update-schedule]
aws_cloudwatch_log_group.lambda-log-group[0]: Creating...
aws_security_group_rule.egress_http[0]: Creation complete after 1s [id=sgrule-1325863533]
aws_cloudwatch_log_group.lambda-log-group[0]: Creation complete after 0s [id=UpdateCloudflareIps]
aws_lambda_function.update-ips[0]: Creating...
aws_lambda_function.update-ips[0]: Still creating... [10s elapsed]

│ Error: AccessDeniedException: 
│ 	status code: 403, request id: 8541d2e5-8408-42ab-a4e5-bce8ad178e88
│ 
│   with aws_lambda_function.update-ips[0],
│   on addon-secure-ingress.tf line 90, in resource "aws_lambda_function" "update-ips":
│   90: resource "aws_lambda_function" "update-ips" {
│ 
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

Tried turn on debug or trace but pretty much the same error without detail
local apply works without problem though.

Does anyone ever see this problem before?
Or any suggestion how to troubleshoot on GitHub action pipeline?

below is my IAM service account permissions
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "events:DeleteRule",
                "iam:PassRole",
                "events:DescribeRule",
                "iam:ListAttachedRolePolicies",
                "events:PutRule",
                "events:ListTagsForResource",
                "events:ListTargetsByRule"
            ],
            "Resource": [
                "arn:aws:iam::929109338894:role/*",
                "arn:aws:events:*:929109338894:rule/*",
                "arn:aws:events:*:929109338894:event-bus/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "lambda:CreateFunction",
                "lambda:UpdateFunctionCode",
                "lambda:ListFunctions",
                "lambda:GetFunction",
                "events:ListRules",
                "lambda:GetCodeSigningConfig",
                "lambda:GetFunctionCodeSigningConfig",
                "lambda:GetPolicy"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by orzarchi** [comment]
Sorry, if this works locally for you, I can't help you.
applying terraform through github actions is out of scope of this repo. try looking at terraform cloud

**Comment by antigenius0910** [comment]
This is actually an AWS iam permission question instead of a GitHub action question
I create a new IAM user and grant it all permission then after it finish the terraform apply I go check event history from cloud trial so now I have all the IAM permission you need in order to run this module

In case anyone need it



Event source | Event name
-- | --
ec2.amazonaws.com | DescribeAccountAttributes
ec2.amazonaws.com | DescribeSecurityGroups
ec2.amazonaws.com | RevokeSecurityGroupEgress
events.amazonaws.com | DeleteRule
events.amazonaws.com | DescribeRule
events.amazonaws.com | ListTagsForResource
events.amazonaws.com | ListTargetsByRule
events.amazonaws.com | PutTargets
events.amazonaws.com | RemoveTargets
iam.amazonaws.com | DeletePolicy
iam.amazonaws.com | DeleteRole
iam.amazonaws.com | DetachRolePolicy
iam.amazonaws.com | GetPolicy
iam.amazonaws.com | GetPolicyVersion
iam.amazonaws.com | GetRole
iam.amazonaws.com | ListAttachedRolePolicies
iam.amazonaws.com | ListInstanceProfilesForRole
iam.amazonaws.com | ListPolicyVersions
iam.amazonaws.com | ListRolePolicies
lambda.amazonaws.com | AddPermission20150331v2
lambda.amazonaws.com | DeleteFunction20150331
lambda.amazonaws.com | GetFunction20150331v2
lambda.amazonaws.com | GetFunctionCodeSigningConfig
lambda.amazonaws.com | GetPolicy20150331v2
lambda.amazonaws.com | ListVersionsByFunction20150331
lambda.amazonaws.com | RemovePermission20150331v2
logs.amazonaws.com | DeleteLogGroup
logs.amazonaws.com | DescribeLogGroups
logs.amazonaws.com | ListTagsLogGroup
logs.amazonaws.com | CreateLogGroup
